### ISSUE TITLE
Github Release and PyPI Version are Out of Sync

### ISSUE THREAD

**Issue by AustinGilliam** [CQCL/pytket#12]
Would it be possible to update the Github release version (currently 0.3.0) so that it corresponds to what is in PyPI (0.4.1)? This helps when requesting open-source libraries be pulled into restricted software development environments.

**Comment by ss2165** [comment]
We were not planning on keeping github releases updated because we are no longer hosting source code on the repository, the repository is now just for documentation and examples. We could still keep posting releases of course if it helps, but I am not sure what it is that you say it would help with? I mostly just want to make sure you aren't trying to pull in pytket source from github, as it is not there any more (and the c++ source was never there).

**Comment by AustinGilliam** [comment]
Sorry, I somehow missed that the repository no longer hosts the source. That resolves the issue for me, thank you!
