### ISSUE TITLE
LinePlacement and GraphPlacement do not accept FullyConnected.

### ISSUE THREAD

**Issue by Le0nerdo** [CQCL/pytket#136]
When using pytket 0.19.2, pytket.routing.GraphPlacement and pytket.routing.LinePlacement do not accept an instance of pytket.routing.FullyConnected as a constructor argument. This problem does not occur when using pytket 0.17.0.

Example of an error message:
```
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pytket._tket.routing.GraphPlacement(arc: pytket._tket.routing.Architecture)

Invoked with: <tket::FullyConnected, nodes=10>
```

**Comment by cqc-alec** [comment]
Hi, thanks for reporting this. Yes, this usage was broken with https://github.com/CQCL/tket/pull/116 which would affect versions from 0.18 on I believe.

Since one of the purposes of that PR was to enable an efficient representation of fully-connected architectures (no graph is stored, just a node set), the solution is probably to overload the existing GraphPlacement and LinePlacement methods with new ones that accept a FullyConnected. (The placement algorithms would be fairly trivial, I think.)

**Comment by cqc-alec** [comment]
https://github.com/CQCL/tket/pull/347
