### ISSUE TITLE
Is there a simple example for inner/outer product of single qubit states?

### ISSUE THREAD

**Issue by Penghmed** [CQCL/pytket#169]

**Comment by CalMacCQ** [comment]
Are there particular examples on the outer product that you would find helpful? It would be good to know more detail about what you are looking for.

**Comment by Penghmed** [comment]
Yes, I am interested in Φ1=(|00> − i|11>), Φ2=(|01> −|11>) and calculate <Φ1|Φ2> and  |Φ1>|Φ2>

Thanks.

**Comment by CalMacCQ** [comment]
Okay the inner product you mentioned can be worked out by hand to be equal to 1*i. This value will change if you normalise the states.

 If you want to calculate inner products using circuits then the SWAP test I mentioned generalises for states with more qubits... You just add some extra CSWAP gates between the two registers. In this case the registers q[1] and q[2] will correspond to multi-qubit states

the |phi1;> |phi2;> term you mentioned is a tensor product. There is some explanation of tensor products here https://www.quantiki.org/wiki/tensor-product. 

The outer product of two statevectors is usually written |phi_1><phi_2| and the answer corresponds to a matrix rather than a scalar or a vector. I've included a screenshot of the outer product of your two states below.

![Screenshot 2022-09-13 at 11 17 35](https://user-images.githubusercontent.com/93673602/189876904-85d0ac2f-c7c8-4b01-b0f8-fc38dd76c04f.png)

I hope this helps - let me know if there is more I can help with.

**Comment by CalMacCQ** [comment]
I will close this issue for now - if you have further questions feel free to get in touch again.

You can also ask questions on our public slack channel -> https://tketusers.slack.com/join/shared_invite/zt-18qmsamj9-UqQFVdkRzxnXCcKtcarLRA#/shared-invite/email
