### ISSUE TITLE
pytket-cirq is too specific when pinning to cirq

### ISSUE THREAD

**Issue by mpharrigan** [CQCL/pytket#22]
xref: https://github.com/quantumlib/ReCirq/issues/61

When trying to install the latest release of cirq, which is `0.8.2`, you get:
```
error: cirq 0.8.2 is installed but cirq==0.8 is required by {'pytket-cirq'}
```

I suspect this is because the pin is too specific. If you change it to `cirq~=0.8` it will work with point releases. Ironically, this point release was to fix some dependency management bugs!

**Comment by cqc-alec** [comment]
Thanks for the report and sorry for the issue this caused. The reason we didn't use `~=0.8` was that this would also accept `0.9` which may not be API-compatible. But as long as we can assume `0.8.x` will be API-compatible with `0.8` we should be fine to change it to `~=0.8.0`.

This will be fixed in the next `pytket-cirq` release.
