### ISSUE TITLE
update to sphinx 6.2

### ISSUE THREAD

**Issue by cqc-melf** [CQCL/pytket#244]

**Comment by dlyongemallo** [comment]
Can you please provide some more details on this?

I'm not sure if this is related, but when I run the `build-manual` script, it seems not to respect the virtual environment, so it would complain about missing modules even when the modules are installed. (The complaints are resolved if i install the missing modules outside of the virtual environment, which I don't want to do.) But this problem happens both in sphinx 6.2.1 and 5.3.0, so it's not specific to sphinx 6.2.

**Comment by cqc-alec** [comment]
@CalMacCQ Do you remember what the issue was with sphinx 6.2? Can we update it?

**Comment by CalMacCQ** [comment]
The issue was using deprecated intersphinx syntax for the `interpshinx_mapping` in `conf.py`

See here -> https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping

I already updated this [here](https://github.com/CQCL/pytket/pull/264/files#diff-a2074e3cf97c2a68a6b48fc16605174c81775c4d0be2fcd92964d4ad19e0a0dc) 

I guess I forgot to close this issue.

**Comment by cqc-alec** [comment]
OK thanks, will close this.

@dlyongemallo I'm not sure what the issue is with the virtual environment, but could you raise a new issue with the modules that seem to be missing? We don't see this issue on CI.

**Comment by dlyongemallo** [comment]
> could you raise a new issue

(For the record, I did this in #272.)
