### ISSUE TITLE
Place with map gives an error

### ISSUE THREAD

**Issue by yourball** [CQCL/pytket#26]
When trying to follow routing_example.ipynb from pytket tutorials and invoking place_with_map(...) function I encounter a strange error:
TypeError: place_with_map(): incompatible function arguments. The following argument types are supported:
    1. (circuit: pytket.circuit.Circuit, qmap: pytket.routing.QubitMap) -> None

It looks like I pass correct arguments, however I still get the error. 
The error occurs both in pytket 0.6.0 and pytket 0.5.4.

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/11663863/93838810-0090cd00-fc59-11ea-9d92-f1d886f7d003.png">

**Comment by cqc-alec** [comment]
Thanks for the report. Running the current (0.6.0-version) notebook with pytket 0.5.4 would indeed give this error, since the signature of `place_with_map` changed slightly to expect a Python dictionary rather than a `QubitMap`. However, you should definitely not get this with pytket 0.6.0. (There is no `QubitMap` class any more.)
Could you please double-check your pytket version (`pip show pytket`), just to be sure that you really are running 0.6.0? The only explanation I can thing of would be an incomplete package upgrade.
If it is not that, could you post your OS and Python version?

**Comment by yourball** [comment]
Thanks a lot for a quick response! Indeed I was using version of pytket < 0.6.0, that was the cause for the error. The issue can be closed, thanks!
