### ISSUE TITLE
pytket 0.7.0 pins to openfermion 0.11

### ISSUE THREAD

**Issue by mpharrigan** [CQCL/pytket#39]
We'd like to use pytket 0.7 with openfermion 1.0+. Is there actually some restriction preventing this from working? Why is pytket using openfermion anyways :)

**Comment by ss2165** [comment]
It's only dependent on openfermion to convert to and from the pytket `QubitPauliOperator`, so it should work fine with 1.0. But since it is not essential for actual functionality, we will drop the OF dependency in the next patch release (0.7.1, out soon) and have a runtime import check for openfermion instead.

**Comment by mpharrigan** [comment]
Sweet, thanks!

**Comment by ss2165** [comment]
pytket 0.7.1 has now been released and the dependency on OpenFermion removed.
